language: php
php:
  - 5.4
before_script:
  - composer selfupdate
  - composer install --dev
  - composer require --dev phpunit/phpunit 3.7.18
script:
  - phpunit --bootstrap=bootstrap.php --coverage-text="php://stdout" --configuration="phpunit.xml" src/Navarr/Socket/Tests
